# Generated by Django 5.2.8 on 2025-11-22 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_categoria_cantidad_categoria_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='imagen',
        ),
    ]
